//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif



#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_MAJOR_UPDATE 0
#define VERSION_MINOR_UPDATE 0

#define VERSION_SHORT MAJOR_VER.MINOR_VER
#define VERSION_SHORT_STR STR(VERSION_SHORT)

#define VERSIONRC_COMPANYNAME "Eibonz"
#define VERSIONRC_FILEDESCRIPTION "Pyfa Darkmode Modification"
#define VERSIONRC_FILEVERSION VERSION_MAJOR,VERSION_MINOR,VERSION_MAJOR_UPDATE,VERSION_MINOR_UPDATE
#define VERSIONRC_FILEVERSION_STR STR(VERSIONRC_FILEVERSION)
#define VERSIONRC_INTERNALNAME "oleacc.dll"
#define VERSIONRC_LEGALCOPYRIGHT "2022 by Eibonz"
#define VERSIONRC_ORIGINALFILENAME VERSIONRC_INTERNALNAME
#define VERSIONRC_PRODUCTNAME VERSIONRC_FILEDESCRIPTION
#define VERSIONRC_PRODUCTVERSION VERSIONRC_FILEVERSION
#define VERSIONRC_PRODUCTVERSION_STR VERSIONRC_FILEVERSION_STR
#define VERSIONRC_FILEFLAGSMASK 0x3fL
