#pragma once

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_MAJOR_UPDATE 2
#define VERSION_MINOR_UPDATE 1

#define VERSION_SHORT MAJOR_VER.MINOR_VER
#define VERSION_SHORT_STR STR(VERSION_SHORT)

#define VERSIONRC_COMPANYNAME "Eibonz"
#define VERSIONRC_FILEDESCRIPTION "Pyfa Darkmode Modification"
#define VERSIONRC_FILEVERSION VERSION_MAJOR,VERSION_MINOR,VERSION_MAJOR_UPDATE,VERSION_MINOR_UPDATE
#define VERSIONRC_FILEVERSION_STR STR(VERSIONRC_FILEVERSION)
#define VERSIONRC_INTERNALNAME "oleacc.dll"
#define VERSIONRC_LEGALCOPYRIGHT "2023 by Eibonz"
#define VERSIONRC_ORIGINALFILENAME VERSIONRC_INTERNALNAME
#define VERSIONRC_PRODUCTNAME VERSIONRC_FILEDESCRIPTION
#define VERSIONRC_PRODUCTVERSION VERSIONRC_FILEVERSION
#define VERSIONRC_PRODUCTVERSION_STR VERSIONRC_FILEVERSION_STR
